---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.1'
      jupytext_version: 1.2.4
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

# Names in Python

```{python}
# Run this cell to set up the notebook, but please don't change it.
# These lines load the tests.
from client.api.assignment import load_assignment
tests = load_assignment('basic_names.ok')
```

**Question 1.** Suppose you can't remember how many planets there are in our solar system.  Your TA, who went to school in the 1990s, says the answer is 9.  In the next cell, give the name `number_of_planets` to the number 9.

```{python}
number_of_planets = ...
```

Run the next cell to test your answer.  You should find that the test fails, and it provides a hint about what went wrong.  Fix your answer in the previous cell, following the hint, so that the test passes.

```{python}
_ = tests.grade('q1')
```

**Question 2.** A famous fact in mathematics is that

$$(1 + \frac{1}{n})^{n}$$

gets very close to the number $e$, which is roughly $2.718$, when $n$ is large.  Use this fact to compute an approximation to $e$, called `roughly_e`.  Your approximation should be correct to at least 5 decimal places.

```{python}
roughly_e = ...
roughly_e
```

```{python}
_ = tests.grade('q2')
```

**Question 3.** In the previous question, you might have noticed that you had to type in the value of $n$ twice when you tried different values (once as `1/n` and once as `**n`).  You might have even accidentally used 2 different values.

Redo the code in the cell below, giving your estimate of $e$ the name
`also_roughly_e`.  Instead of writing the value of $n$ twice, give it the name
`n` in your Python code, and then use that name in your expression for
`also_roughly_e`.

```{python}
n = ...
also_roughly_e = ...
also_roughly_e
```

```{python}
_ = tests.grade('q3')
```

```{python}
# For your convenience, you can run this cell to run all the tests at once!
import os
_ = [tests.grade(q[:-3]) for q in os.listdir("tests") if q.startswith('q')]
```

## Notes

From [the Berkeley course materials](https://github.com/data-8/data8assets) with thanks.
