---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.0'
      jupytext_version: 0.8.4
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
  language_info:
    codemirror_mode:
      name: ipython
      version: 3
    file_extension: .py
    mimetype: text/x-python
    name: python
    nbconvert_exporter: python
    pygments_lexer: ipython3
    version: 3.7.0
---

# Names in Python


## The OKpy system


This notebook uses the [OKpy](https://okpy.org) automatic testing system.  OKpy provides checks for you to test whether you have got the right input.  You'll see those checks further down the notebook, as you work.  They allow you see if you are on the right track.

For now, just execute the cell below to get the stuff we need from the OKpy library.

If you get an error:

    LoadingException: No tests loaded

then make sure you have extracted the exercise zip file correctly.  See the
[extracting](https://matthew-brett.github.io/cfd2019/extracting) page for
instructions.

If you see errors like `name 'ok' is not defined` further down in this
notebook, find this cell again, and execute it.

```{python}
# Run this cell to set up the notebook, but please don't change it.
# These lines load the tests.
from client.api.notebook import Notebook
ok = Notebook('basic_names.ok')
```

If you got an error - see above for suggestions.

If not, you are ready for question 1.


**Question 1.** Suppose you can't remember how many planets there are in our solar system.  Your TA, who went to school in the 1990s, says the answer is 9.  In the next cell, give the name `number_of_planets` to the number 9.

```{python}
number_of_planets = 8
```

Run the next cell to test your answer.  You should find that the test fails, and it provides a hint about what went wrong.  Fix your answer in the previous cell, following the hint, so that the test passes.

```{python}
_ = ok.grade('q1')
```

**Question 2.** A famous fact in mathematics is that

$$(1 + \frac{1}{n})^{n}$$

gets very close to the number $e$, which is roughly $2.718$, when $n$ is large.  Use this fact to compute an approximation to $e$, called `roughly_e`.  Your approximation should be correct to at least 5 decimal places.

```{python}
roughly_e = (1 + 1 / 100000) ** 100000
roughly_e
```

```{python}
_ = ok.grade('q2')
```

**Question 3.** In the previous question, you might have noticed that you had to type in the value of $n$ twice when you tried different values (once as `1/n` and once as `**n`).  You might have even accidentally used 2 different values.

Redo the code in the cell below, giving your estimate of $e$ the name
`also_roughly_e`.  Instead of writing the value of $n$ twice, give it the name
`n` in your Python code, and then use that name in your expression for
`also_roughly_e`.

```{python}
n = 100000
also_roughly_e = (1 + 1 / n) ** n
also_roughly_e
```

```{python}
_ = ok.grade('q3')
```

```{python}
# For your convenience, you can run this cell to run all the tests at once!
import os
_ = [ok.grade(q[:-3]) for q in os.listdir("tests") if q.startswith('q')]
```

## Notes

From [the Berkeley course materials](https://github.com/data-8/data8assets) with thanks.
