---
jupyter:
  jupytext:
    notebook_metadata_filter: all,-language_info
    split_at_heading: true
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.1'
      jupytext_version: 1.2.4
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

In the [reverse probability page]({{ site.baseurl }}/chapters/10/first_bayes)
we played a game with two boxes, with different proportions of red and green
balls.

The [Bayes bars page]({{ site.baseurl }}/chapters/10/bayes_bars) has a way of thinking of our calculations for this game, using the height of bars to express our probabilities.

Now we extend the game to more options.

Now I have five boxes:

* box1 has one red ball and four green balls.
* box2 has two red balls and three green balls.
* box3 has three red balls and two green balls.
* box4 has four red balls and one green ball.
* box5 has five red balls.

* I offer you one of these five boxes at random, without telling you which.
* You draw a ball at random from the box, and you get a red ball.
* Now, what is the probability that I gave you box4?

We can solve this by simulation, of course, but lets solve it using the bars from the [Bayes bars page]({{ site.baseurl }}/chapters/10/bayes_bars).

First we express the initial probabilities of getting the five boxes:

```{python}
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline
```

```{python}
box_probabilities = np.repeat(1 / 5, 5)
x_locations = np.arange(5)
box_labels = ['box1', 'box2', 'box3', 'box4', 'box5']
plt.bar(x_locations, box_probabilities)
plt.xticks(x_locations, box_labels)
plt.ylabel("Probability of getting box")
plt.title('Initial probability of boxes');
```

Next we express the initial probabilities of getting a red ball from boxes 1 through 5:

```{python}
red_probabilities = np.array([1, 2, 3, 4, 5]) / 5
plt.bar(x_locations, red_probabilities)
plt.xticks(x_locations, box_labels)
plt.ylabel("Probability of getting red ball")
plt.title('Probability of getting red for each box');
```

Next we combine the two steps, of getting a box, and then drawing a ball.

As before, we do this by multiplying the values expressed by heights in the
first bar graph, by the values expressed by heights in the second bar graph.

```{python}
box_and_red_probs = box_probabilities * red_probabilities
plt.bar(x_locations, box_and_red_probs)
plt.xticks(x_locations, box_labels)
plt.ylabel("Probability of getting red ball and the given box")
plt.title('Probability of getting red and each box');
```

In this case, as before, where all the initial probabilities of the boxes are
the same, this last bar graph is just the second bar graph scaled down by 1/5.


Lastly, remember we are interested in the probability that we started with box4, given we have a red ball.

To get this probability, we first take the probability of getting a red ball *and* box4.  This is the fourth bar on the graph above - 0.2 * 0.8 = 0.4.

Next we divide by the overall probability of getting a red ball, which is the sum of the heights of the five bars above.

We can do this calculation by dividing the heights of the bars above by the sum of the heights, so the heights of the bars now sum to 1.

The sum of the heights is:

```{python}
# Overall probability of getting a red ball.
np.sum(box_and_red_probs)
```

Here are the bars divided by this sum:

```{python}
box_given_red_probs = box_and_red_probs / np.sum(box_and_red_probs)
plt.bar(x_locations, box_given_red_probs)
plt.xticks(x_locations, box_labels)
plt.ylabel("Probability of box given a red ball")
plt.title('Probability of initial box given red ball drawn');
```
