---
jupyter:
  jupytext:
    notebook_metadata_filter: all,-language_info
    split_at_heading: true
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.1'
      jupytext_version: 1.2.4
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

# Simulation exercises

```{python}
# Don't change this cell; just run it.
import numpy as np  # The array library.

# The OKpy testing system.
from client.api.notebook import Notebook
ok = Notebook('simulation.ok')
```

## Penalty shootout technique

Jen is the penalty taker for her football team.

She's been doing this for a long time.  She thinks she normally has a 80%
chance of scoring.

In the last 15 penalties she has taken, she has been trying a new technique.
She scored on all 15 penalties.

How certain can she be that this would not have happened, using the old
technique?

Hint: consider `np.random.randint`.  Read the help with `np.random.randint?`.

```{python}
#- Calculate the probability of Jen scoring 15 out of 15 penalties.
#<- p_15_of_15 = ...
counts = np.zeros(10000)
for i in np.arange(10000):
    shots = np.random.randint(0, 10, 15)
    scores = np.count_nonzero(shots < 8)
    counts[i] = scores
p_15_of_15 = np.count_nonzero(counts == 15) / 10000
#<--
p_15_of_15
```

```{python}
_ = ok.grade('q_1_penalties')
```

## Aim big

John is playing Monopoly.  His piece, the top hat, is sitting in a really bad
spot, just in front of some expensive hotels.  He is about to roll the two
6-sided die.  He needs a score of 10 or more to skip over the hotels.  What
are John's chances?

Solve by simulation.

Hint: consider `np.random.randint` again.

```{python}
#- Calculate the probability of getting 10 or more with two dice.
#<- p_10_or_more = ...
counts = np.zeros(10000)
for i in np.arange(10000):
    dice = np.random.randint(1, 7, 2)
    score = np.sum(dice)
    counts[i] = score
p_10_or_more = np.count_nonzero(counts >= 10) / 10000
#<--
p_10_or_more
```

```{python}
_ = ok.grade('q_2_monopoly')
```

## Blackjack

Given any three random playing cards, what is the chance that the ranks of the
three cards add up to 21?

10, jack, queen and king all count as 10.  For example, one way of getting 21
is a seven, a four and a king.


### Simple version

Assume the three cards are each dealt from the top of a full shuffled deck.
Therefore, the procedure is:

* you shuffle, look at the top card, record the rank, you put it back.
* repeat twice more.

Assume that the ace counts as 1.  What are the chances of getting
a total rank of 21?

Hint: look at the array `ranks` in the code cell below.

Investigate `np.random.choice` to use this array for the problem.

```{python}
#<-
# Ranks of all the cards in one suit.
ranks = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 10, 10, 10])
#<-
#<- p_total_21 = ...
rank_totals = np.zeros(10000)
for i in np.arange(10000):
    cards = np.random.choice(ranks, 3)
    rank_totals[i] = np.sum(cards)
p_total_21 = np.count_nonzero(rank_totals == 21) / 10000
#<--
p_total_21
```

```{python}
_ = ok.grade('q_3_simple_blackjack')
```

## Less simple version

Assume the cards are drawn as they were for the problem above.

Now the ace can count as 1 or as 11, whichever gives a total of 21.  To make things a bit simpler, the two options are:

* all aces in a hand count as 1, OR
* all aces in a hand count as 11.

Your job is to choose the option from the list above, that gives you 21, if that is possible.

For example, if you have a hand (Ace, Ace, 9), then your two options are ranks
(1, 1, 9) (for a total of 21) or (11, 11, 9) (for a total of 31), in which
case you would choose the ace = 1 rank.  On the other hand, you might have
(Ace, 2, 8) in which case you would chose the ace = 11 rank.  In this
simplified case (Ace, Ace, 8) can only give 10 (for ace=1) or 30 (for ace=11).

In this situation, what are the chances of a total rank of 21?

The hints below are for one way of solving this case.   There are other ways of solving this case; feel free to chose the method you prefer.

*Hint 1*: you can change values of 1 to 11 like this:

```{python}
# Make an example array
some_cards = np.array([1, 3, 5, 1, 2])
some_cards
```

```{python}
# Make a Boolean array that has True for positions where some_cards == 1
card_eq_1 = some_cards == 1
card_eq_1
```

```{python}
# In the found positions, change the value to 11
some_cards[card_eq_1] = 11
some_cards
```

*Hint 2*: You might want to use this kind of trick more than once in your
solution.

*Hint 3*: You might consider having two arrays of results for each hand, one for the case where aces count as 1 and the other for case where aces count as 11, like this:

```{python}
# Initialize result arrays.
rank_totals_1 = np.zeros(10000)
rank_totals_11 = np.zeros(10000)
```

Here is the cell for your solution:

```{python}
rank_totals_1 = np.zeros(10000)
rank_totals_11 = np.zeros(10000)
for i in np.arange(10000):
    cards = np.random.choice(ranks, 3)
    rank_totals_1[i] = np.sum(cards)
    cards[cards == 1] = 11
    rank_totals_11[i] = np.sum(cards)
rt_11s = rank_totals_11 == 21
rank_totals_1[rt_11s] = 21
p_flex_total_21 = np.count_nonzero(rank_totals_1 == 21) / 10000
#<- p_flex_total_21 = ...
#<--
p_flex_total_21
```

```{python}
_ = ok.grade('q_4_flexi_blackjack')
```

You may have found that allowing aces to count as 11 didn't greatly improve your chances of getting 21.  Why is that?

## Done.

Congratulations, you're done with the assignment!  Be sure to:

- **run all the tests** (the next cell has a shortcut for that),
- **Save and Checkpoint** from the `File` menu,

```{python}
# For your convenience, you can run this cell to run all the tests at once!
import os
_ = [ok.grade(q[:-3]) for q in os.listdir("tests") if q.startswith('q')]
```
