---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.1'
      jupytext_version: 1.2.4
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

# Basic Arithmetic in Python

This set of exercises gives you practice writing basic arithmetic expressions in Python.


**Question 1.** In the next cell, write a Python expression equivalent to this math expression:

$$1 - \frac{2^2}{2^{20}}$$

The value of the expression is around 0.999996.  After you have something that works, try to improve your solution by using only as many parentheses as you need.

```{python}
1 - 2**2 / 2**20 #SOLUTION
```

**Question 2.** Try to predict the value of the expression in the next cell.  Before you run the cell, write your prediction in the cell below it.

```{python}
1 - 2 ** 3 / 4 + 5 * 6
```

```{python}
# Your prediction here:
29 #SOLUTION
```

**Question 3.** Try to predict whether the value of the expression below is larger or smaller than the value of the expression in the previous question.  You can use the next cell to record your answer.  Then run the cell to see what happens.  If you were wrong, figure out why, and include that in your written answer.

```{python}
1 - 2 ** (3 / 4 + 5 * 6)
```

**SOLUTION:** It's smaller.  The first cell subtracts $2^{3/4}$ from the total, which is a number smaller than 2.  The second cell instead subtracts $2^{(3/4) + (5 \times 6)}$, which is bigger than $2^{30}$, which is a fairly large number.


**Question 4.** A famous fact in mathematics is that

$$(1 - \frac{1}{n})^{-n}$$

gets very close to the number $e$, which is roughly $2.718$, when $n$ is large.  Verify that it gets closer to $e$ as $n$ gets larger by writing this expression in Python and trying different values for $n$.

*Hint:* If you write several expressions in a cell, only the last will be printed.  If you want to see the values of several copies of the expression at once, put `print(...)` around them, as in Lab 1.

```{python}
(1 - 1/100000)**(-100000) #SOLUTION
```

## Notes

From [the Berkeley course
materials](https://github.com/data-8/data8assets) with
thanks.
