---
jupyter:
  jupytext:
    notebook_metadata_filter: all,-language_info
    split_at_heading: true
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.1'
      jupytext_version: 1.2.4
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

# Selecting values from an array

```{python}
import numpy as np
```

We use arrays all the time, in data science.

One of the most common tasks we have to do on arrays, is to select values.

We do this with *array slicing*.

We do array slicing when we follow the array variable name with
`[` (open square brackets), followed by something to specify
which elements we want, followed by `]` (close square brackets.

The simplest case is when we want a single element from a one-dimensional array.  In that case the thing between the `[` and the `]` is the *index* of the value that we want.

The *index* of the first value is 0, the index of the second value is 2, and so on.

We start by loading data from a Comma Separated Value file (CSV
file).  If you are running on your laptop, you should download
the [gender_stats.csv]({{ site.baseurl }}/data/rate_my_course.csv)
file to the same directory as this notebook.

Don't worry about the next cell.  It just loads the data we need from a data file.  We will come on the machinery to do this very soon.

```{python}
# This code we have not covered yet.  We will soon.
# Load the data file
import pandas as pd
courses = pd.read_csv('rate_my_course.csv').sort_values(
    'Easiness', ascending=False).head(10)
disciplines = courses['Discipline'].values
easiness = courses['Easiness'].values
disciplines
```

Here we get the first value.  This value is at index 0.

```{python}
# Get the first value (at index position 0)
disciplines[0]
```

```{python}
# Get the second value (at index position 1)
disciplines[1]
```

```{python}
# Get the third value (at index position 2)
disciplines[2]
```

At first this will take some time to get used to, that the first
value is at index position 0.  There are good reasons for this,
and many programming languages have this convention, but it does a while to get this habit of mind.

## Index with negative numbers


If we know how many elements the array has, then we can get the last element by using the number of elements, minus one (why?).

Here the number of elements is 10:

```{python}
len(disciplines)
```

So, the last element of the array is at index position 9:

```{python}
disciplines[9]
```

In fact, there is a short cut for getting elements at the end of the array, and that is to use an offset with a minus in front.  The number is then the offset from one past the last item.  For example, here is another way to get the last element:

```{python}
disciplines[-1]
```

The last but one element:

```{python}
disciplines[-2]
```

## Index with slices


Sometimes we want more than one element from the array.  For example, we might want the first 5 elements from the array.  We can get these using an array *slice*.  It looks like this:

```{python}
# All the elements from offset zero up to (not including) 5
disciplines[0:5]
```

```{python}
# All the elements from offset 5 up to (not including) 10
disciplines[5:10]
```

You can omit the first number, if you mean to start at offset 0:

```{python}
disciplines[:5]
```

You can omit the last number if you mean to end at the last element of the array:

```{python}
disciplines[5:]
```

## Indexing with Boolean arrays

We often want to select several elements from an array according to some criterion.

The most common way to do this, is to do array slicing, using
a Boolean array between the square brackets.

It may be easier to understand this by example.

You have already come across Boolean arrays.

These are arrays of `True` and `False` values.

```{python}
easiness
```

Here is a Boolean array, created from applying a comparison to an array:

```{python}
greater_than_3p5 = easiness > 3.5
greater_than_3p5
```

As you have already seen, we can do things like count the number
of `True` values in the Boolean array:

```{python}
np.count_nonzero(greater_than_3p5)
```

Now let us say that we wanted to get the elements from `randoms`
that are less than 0.5.   That is, we want to get the elements
in `randoms` for which the corresponding element in
`less_than_0p5` is `True`.

We can do this with *Boolean array indexing*.  The Boolean array goes between the square brackets, like this:

```{python}
easiness[greater_than_3p5]
```

We have selected the numbers in `easiness` that are greater than 3.5.


We can use this same Boolean array to index into another array.  For example, here we show the discipline *names* corresponding to the courses that are easier than 3.5:

```{python}
disciplines[greater_than_3p5]
```

```{python}
courses.head(10)
```

## Exercises

See the [array indexing exercises](../exercises/array_indexing).
