---
jupyter:
  jupytext:
    split_at_heading: true
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.1'
      jupytext_version: 1.2.4
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

So far we have used function arguments in a basic way; this is the way that is familiar from mathematics:

```{python}
# Load the Numpy package, and rename to "np"
import numpy as np
```

```{python}
np.cos(0)
```

Here is another Numpy function, from the `random` sub-package of the Numpy library.  We get to the sub-packages with the dot `.` - so to get to the `random` sub-package, we use `np.random`.  Then, to get to the functions in this sub-package, we use the dot again, like this:

```{python}
np.random.randint(2)
```

Remember, this is a random integer from 0 up to, but *not including* 2, so it is a random integer that can either be 0 or 1.

Now let us look at the help for the `np.random.randint` function.  As usual, we do this by appending `?` to the function name, and pressing Enter in the notebook.

```{python}
# To see the help for np.random.randint, remove the # at the beginning
# of the next line, and execute this cell.
# np.random.randint?
```

We find that the function can accept up to four arguments.  We have only passed one, and that sets the argument called `high`.

Now let us pass two arguments, to set the argument called `low` and the
argument called `high`.  In this case we are asking for a random number
starting at 1 up to, but not including 11. This gives us a random integer from
1 through 10. `low` is 1 and `high` is 11.


```{python}
# Random integer from 1 through 10.
np.random.randint(1, 11)
```

Notice that, if we just pass one argument, that argument is the `high` argument.   In that case, the function sets the `low` argument for us, and sets to the *default* value, of 0.  So, the cell below is exactly equivalent to our first call to this function: `np.random.randint(2)`:

```{python}
# Random integer from 0 through 2.
np.random.randint(0, 2)
```

If we pass three arguments, we also set the `size` argument.  This tells the function how many random numbers to return.  The following asks for an array of four random integers from 1 through 20:

```{python}
# Four random integers from 1 through 20.
np.random.randint(1, 21, 4)
```

Notice that this is an *array*.

Now look again at the help.  Notice that the help gives each argument a *name* - `low`, `high`, `size`.  We can also use these names when we set these arguments.  For example, the cell below does exactly the same thing as the cell above.

When we call the function using the arguments with their names like this, the named arguments are called *keyword* arguments.

```{python}
# Four random integers from 1 through 20, using keyword arguments.
np.random.randint(low=1, high=21, size=4)
```

Keyword arguments can be very useful, to make it clearer what each argument means.  They also allow us to skip some arguments, and just pass in the ones we want.

For example, we already know that if we just pass one argument, this is the `high` value:

```{python}
np.random.randint(2)
```

We might want to specify the `high` value and the `size` value, but let the `low` value remain at its default of 0.  We can do that by specifying the `high` value as normal, then using `size=4` to jump ahead, and specify the `size` value:

```{python}
np.random.randint(2, size=4)
```

Here, we leave `low` at the default (0), we specify `high`, and then we change
the default for `size` to 4, to ask for an array of four random integers.
