---
jupyter:
  jupytext:
    split_at_heading: true
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.1'
      jupytext_version: 1.2.4
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

We are still building up to a solution for the [three girls
problem](../02/three_girls).

We have more of the building blocks we need.

First we load the Numpy library.

```{python}
# Load the Numpy package, and rename to "np"
import numpy as np
```

We are going to simulate 10000 families, each with four children.

Here we put together some things you've seen before.  We are creating a Numpy array from an empty list.  We get an empty array.

```{python}
# Make an empty array to store counts of girls in each family
counts = np.array([])
counts
```

`counts` will eventually have 10000 elements where each will be the number of girls in one simulated family.

Remembering [function arguments](function_arguments), here is how we make
an array that simulates a family of four children:

```{python}
family = np.random.randint(2, size=4)
family
```

We represented girls with a value of one. We can count the number of girls by using the `np.sum` function on the `family` array:

```{python}
count = np.sum(family)
count
```

We want to build up a lot of counts, in the `counts` array, so we start by appending the `count` value:

```{python}
# Store the count in the counts array.
counts = np.append(counts, count)
counts
```

We can do this again in a single cell, like this:

```{python}
# A second family
family = np.random.randint(2, size=4)
count = np.sum(family)
# Store the count in the counts array.
counts = np.append(counts, count)
counts
```

To add another family, we just repeat the same:

```{python}
# A third family
family = np.random.randint(2, size=4)
count = np.sum(family)
# Store the count in the counts array.
counts = np.append(counts, count)
counts
```

Obviously this is getting a bit boring and repetitive. Surely we can do better.

Yes indeed, we can use a *for loop*.  Here's a preview:

```{python}
# Reset the counts array to empty.
counts = np.array([])
# Repeat the indented stuff 10000 times.
for i in np.arange(10000):
    # The procedure for one family.
    family = np.random.randint(2, size=4)
    count = np.sum(family)
    # Store the count in the counts array.
    counts = np.append(counts, count)
counts
```

Now we have a count of the number of girls, from 10000 simulated families:

```{python}
len(counts)
```

How did that work?  On to [iteration with for loops](Iteration).
